config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :genres
  resources :directors
  resources :movies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/director.rb
class Director < ApplicationRecord
  has_many :movies
  belongs_to :genre
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
  enum status: { released: 0, not_released: 1 }

  belongs_to :director
  belongs_to :genre

  has_one_attached :poster
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  def index
    @directors = Director.all
  end

  def new
    @director = Director.new
  end

  def create
    @director = Director.new(
      name: params[:director][:name],
      nationality: params[:director][:nationality],
      birth_date: params[:director][:birth_date],
      genre_id: params[:director][:genre_id]
    )

    if @director.save
      flash[:notice] = 'Novo diretor cadastrado com sucesso!'
      return redirect_to director_path(@director.id)
    end

    render :new
  end

  def show
    @director = Director.find(params[:id])
    @movies = Movie.where(director: @director)
  end

  def edit
    @director = Director.find(params[:id])
  end

  def update
    @director = Director.find(params[:id])

    if @director.update(
      name: params[:director][:name],
      nationality: params[:director][:nationality],
      birth_date: params[:director][:birth_date],
      genre_id: params[:director][:genre_id]
    )
      flash[:notice] = "Dados atualizados!"
      return redirect_to director_path(@director.id)
    end

    render :edit
  end

  def destroy
    director = Director.find(params[:id])
    director.destroy

    flash[:notice] = 'Diretor excluído com sucesso!'
    redirect_to directors_path
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(name: params[:genre][:name])

    if @genre.save
      flash[:notice] = 'Novo gênero cadastrado com sucesso!'
      return redirect_to genres_path
    end

    render :new
  end

  def show
    @genre = Genre.find(params[:id])
    @movies = Movie.where(genre: @genre)
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])

    if @genre.update(name: params[:genre][:name])
      flash[:notice] = "Dados atualizados!"
      return redirect_to genre_path(@genre.id)
    end

    render :edit
  end

  def destroy
    genre = Genre.find(params[:id])
    genre.destroy

    flash[:notice] = 'Gênero excluído com sucesso!'
    redirect_to genres_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @movies = Movie.all
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @released = Movie.released
    @not_released = Movie.not_released
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(
      title: params[:movie][:title],
      release_date: params[:movie][:release_date],
      release_year: params[:movie][:release_date].to_date.year,
      synopsis: params[:movie][:synopsis],
      origin: params[:movie][:origin],
      length: params[:movie][:length],
      director_id: params[:movie][:director_id],
      genre_id: params[:movie][:genre_id],
      status: check_release_status(params[:movie][:release_date]),
    )

    if @movie.save
      @movie.poster.attach(params[:movie][:poster])
      flash[:notice] = 'Novo filme cadastrado com sucesso!'
      return redirect_to movie_path(@movie.id)
    end

    render :new
  end

  def show
    @movie = Movie.find(params[:id])
    @status = 'Não lançado'
    @status = 'Lançado' if @movie.status == 'released'
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update(
      title: params[:movie][:title],
      release_date: params[:movie][:release_date],
      release_year: params[:movie][:release_date].to_date.year,
      synopsis: params[:movie][:synopsis],
      origin: params[:movie][:origin],
      length: params[:movie][:length],
      director_id: params[:movie][:director_id],
      genre_id: params[:movie][:genre_id],
      status: check_release_status(params[:movie][:release_date]),
    )
      @movie.poster.attach(params[:movie][:poster])
      flash[:notice] = 'Dados atualizados!'
      return redirect_to movie_path(@movie.id)
    end

    render :edit
  end

  def destroy
    puts "Params #{params}"
    movie = Movie.find(params[:id])
    movie.destroy

    flash[:notice] = 'Filme excluído com sucesso!'
    redirect_to movies_path
  end

  private

  def check_release_status(release_date)
    already_released = Time.now.after? release_date

    return 0 if already_released
    1
  end

  def movie_params
    params.require(:movie).permit(
      :title, :release_date, :synopsis, :origin,
      :length, :director_id, :genre_id, :poster
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/directors/_form.html.erb
<%= form_with model: director do |f| %>
  <div>
    <%= f.label 'Nome' %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label 'Nacionalidade' %>
    <%= f.text_field :nationality %>
  </div>
  <div>
    <%= f.label 'Data de nascimento' %>
    <%= f.date_field :birth_date %>
  </div>
  <div>
    <%= f.label 'Gênero favorito' %>
    <%= f.collection_select :genre_id, Genre.all, :id, :name %>
  </div>
  <div>
    <%= f.submit 'Salvar' %>
  </div>
<% end %>

<div class="back">
  <%= link_to 'Voltar para Diretores', directors_path %>
</div>

app/views/directors/edit.html.erb
<%= button_to 'Excluir este diretor', director_path(@director.id),
  method: :delete, data: { turbo_confirm: 'Confirma exclusão?' } %>
<div class="form">
  <%= render partial: 'form', locals: { director: @director } %>
</div>

app/views/directors/index.html.erb
<h2>Diretores cadastrados</h2>

<% if flash[:notice] %>
  <div>
    <h3><%= flash[:notice] %></h3>
  </div>
<% end %>

<% if @directors.empty? %>
  <p>Nenhum diretor cadastrado</p>
<% end %>

<% @directors.each do |director| %>
  <div>
      <%= director.name %> | 
      <%= link_to 'Detalhes', director_path(director.id) %> |
      <%= link_to 'Editar', edit_director_path(director.id) %>
  </div>
<% end %>

<div class="new">
  <%= link_to 'Cadastrar novo diretor', new_director_path %>
</div>

app/views/directors/new.html.erb
<%= render partial: 'form', locals: { director: @director } %>

app/views/directors/show.html.erb
<% if flash[:notice] %>
  <div>
    <h3><%= flash[:notice] %></h3>
  </div>
<% end %>

<div>
  <h2><%= @director.name %></h2>
</div>
<div>
  <strong>Nacionalidade: </strong><%= @director.nationality %>
</div>
<div>
  <strong>Data de nascimento: </strong><%= @director.birth_date.strftime('%d/%m/%Y') %>
</div>
<div>
  <strong>Gênero favorito: </strong><%= @director.genre.name %>
</div>
<div>
  <strong>Filmes cadastrados: </strong>
  <% if @movies.empty? %>
    <p>Nenhum filme deste diretor cadastrado</p>
  <% else %>
    <ul>
      <% @movies.each do |movie| %>
        <li><%= movie.title %></li>
      <% end %>
    </ul>
  <% end %>
</div>

<div class="edit">
  <%= link_to 'Editar diretor', edit_director_path(@director.id) %>
</div>

<div class="back">
  <%= link_to 'Voltar para Diretores', directors_path %>
</div>

app/views/genres/_form.html.erb
<%= form_with model: genre do |f| %>
    <div>
        <%= f.label 'Nome' %>
        <%= f.text_field :name %>
    </div>
    <div>
        <%= f.submit 'Salvar' %>
    </div>
<% end %>

<div class="back">
  <%= link_to 'Voltar para Gêneros', genres_path %>
</div>

app/views/genres/edit.html.erb
<%= button_to 'Excluir este gênero', genre_path(@genre.id),
   method: :delete, data: { turbo_confirm: 'Confirma exclusão?' } %>
<div class="form">
  <%= render partial: 'form', locals: { genre: @genre } %>
</div>

app/views/genres/index.html.erb
<h2>Gêneros cadastrados</h2>

<% if flash[:notice] %>
  <div>
    <h3><%= flash[:notice] %></h3>
  </div>
<% end %>

<% if @genres.empty? %>
  <p>Nenhum gênero cadastrado</p>
<% end %>

<% @genres.each do |genre| %>
  <div>
      <%= genre.name %> | 
      <%= link_to 'Detalhes', genre_path(genre.id) %> | 
      <%= link_to 'Editar', edit_genre_path(genre.id) %>
  </div>
<% end %>

<div class="new">
  <%= link_to 'Cadastrar novo gênero', new_genre_path %>
</div>

app/views/genres/new.html.erb
<%= render partial: 'form', locals: { genre: @genre } %>

app/views/genres/show.html.erb
<% if flash[:notice] %>
  <div>
    <h3><%= flash[:notice] %></h3>
  </div>
<% end %>

<div>
  <h2>Filmes do gênero <%= @genre.name %></h2>
</div>

<% if @movies.empty? %>
  <p>Nenhum filme com este gênero cadastrado</p>
<% else %>
  <ul>
    <% @movies.each do |movie| %>
      <li><%= movie.title %></li>
    <% end %>
  </ul>
<% end %>

<div class="edit">
  <%= link_to 'Editar gênero', edit_genre_path(@genre.id) %>
</div>

<div class="back">
  <%= link_to 'Voltar para Gêneros', genres_path %>
</div>

app/views/home/index.html.erb
<div>
  <%= link_to 'Gêneros', genres_path %>
</div>
<div>
  <%= link_to 'Diretores', directors_path %>
</div>
<div>
  <%= link_to 'Filmes', movies_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatalogoDeFilmes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <h1>Catálogo de filmes</h1>
    
    <%= yield %>

    <div class="home">
      <%= link_to 'Home', root_path %>
    </div>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with model: movie do |f| %>
  <div>
    <%= f.label 'Título' %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label 'Data de lançamento' %>
    <%= f.date_field :release_date %>
  </div>
  <div>
    <%= f.label 'Sinopse' %>
    <%= f.text_area :synopsis %>
  </div>
  <div>
    <%= f.label 'País de origem' %>
    <%= f.text_field :origin %>
  </div>
  <div>
    <%= f.label 'Duração em minutos' %>
    <%= f.number_field :length %>
  </div>
  <div>
    <%= f.label 'Diretor' %>
    <%= f.collection_select :director_id, Director.all, :id, :name %>
  </div>
  <div>
    <%= f.label 'Gênero' %>
    <%= f.collection_select :genre_id, Genre.all, :id, :name %>
  </div>
  <div>
    <%= f.label 'Poster' %>
    <%= f.file_field :poster %>
  </div>
  <div>
    <%= f.submit 'Salvar' %>
  </div>
<% end %>

<div class="back">
  <%= link_to 'Voltar para Filmes', movies_path %>
</div>

app/views/movies/edit.html.erb
<%= button_to 'Excluir este filme', movie_path(@movie.id),
  method: :delete, data: { turbo_confirm: 'Confirma exclusão?' } %>
<div class="form">
<div>
  <%= render partial: 'form', locals: { movie: @movie } %>
</div>

app/views/movies/index.html.erb
<h2>Filmes cadastrados</h2>

<% if flash[:notice] %>
  <div>
    <h3><%= flash[:notice] %></h3>
  </div>
<% end %>

<h3>Lançados</h3>
<% if @released.empty? %>
  <p>Nenhum filme lançado cadastrado</p>
<% end %>
<% @released.each do |movie| %>
  <div>
      <% if movie.poster.attached? %>
        <div>
          <%= image_tag movie.poster, class: 'list_poster' %>
        </div>
      <% end %>
      <%= link_to "#{movie.title} - #{movie.release_year}",
        movie_path(movie.id), class: 'movie_link' %> |
      <%= link_to 'Detalhes', movie_path(movie.id) %> |
      <%= link_to 'Editar', edit_movie_path(movie.id) %> 
      <hr>
  </div>
<% end %>

<h3>Não lançados</h3>
<% if @not_released.empty? %>
  <p>Nenhum filme não lançado cadastrado</p>
<% end %>
<% @not_released.each do |movie| %>
  <div>
      <% if movie.poster.attached? %>
        <div>
          <%= image_tag movie.poster, class: 'list_poster' %>
        </div>
      <% end %>
      <%= link_to "#{movie.title} - #{movie.release_year}",
        movie_path(movie.id), class: 'movie_link' %> |
      <%= link_to 'Detalhes', movie_path(movie.id) %> |
      <%= link_to 'Editar', edit_movie_path(movie.id) %>
      <hr>
  </div>
<% end %>

<div class="new">
  <%= link_to 'Cadastrar novo filme', new_movie_path %>
</div>

app/views/movies/new.html.erb
<%= render partial: 'form', locals: { movie: @movie } %>

app/views/movies/show.html.erb
<% if flash[:notice] %>
  <div>
    <h3><%= flash[:notice] %></h3>
  </div>
<% end %>

<div>
  <h2><%= @movie.title %></h2>
</div>
<div>
  <strong>Título: </strong><%= @movie.title %>
</div>
<div>
  <strong>Ano de lançamento: </strong><%= @movie.release_year %>
</div>
<div>
  <strong>Sinopse: </strong><%= @movie.synopsis %>
</div>
<div>
  <strong>País de origem: </strong><%= @movie.origin %>
</div>
<div>
  <strong>Duração: </strong><%= @movie.length %> minutos
</div>
<div>
  <strong>Diretor: </strong><%= @movie.director.name %>
</div>
<div>
  <strong>Gênero: </strong><%= @movie.genre.name %>
</div>
<div>
  <strong>Data de lançamento: </strong><%= @movie.release_date.strftime('%d/%m/%Y') %>
</div>
<div>
  <strong>Status: </strong><%= @status %>
</div>

<% if @movie.poster.attached? %>
  <div>
    <%= image_tag @movie.poster, class: 'detail_poster' %>
  </div>
<% end %>

<div class="edit">
  <%= link_to 'Editar', edit_movie_path(@movie.id) %>
</div>

<div class="back">
  <%= link_to 'Voltar para Filmes', movies_path %>
</div>